name: PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v4.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: fix,feat,chore,docs,style,refactor,perf,test
          scopes: DEVS,INT
          validateSingleCommit: false